Replace unused assigment by a cast
This fix compilation error with clang like

clang -DHAVE_CONFIG_H -I.     -Wall -Wextra -std=c99 -pedantic -D_XOPEN_SOURCE=600 -pipe -Werror -DNDEBUG -O3 -MT exec_case.o -MD -MP -MF .deps/exec_case.Tpo -c -o exec_case.o `test -f 'src/exec/exec_case.c' || echo './'`src/exec/exec_case.c
src/exec/exec_case.c:18:8: error: explicitly assigning value of variable of type 's_case_node *' (aka 'struct case_node *') to itself [-Werror,-Wself-assign]
  node = node;
  ~~~~ ^ ~~~~
1 error generated.